# -*- coding: utf-8 -*-
"""calculo.basico

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13tESCt95f7dIpx7uhw4YYVS7IIxmCnYa
"""

soma = 1 + 1
multiplicacao = 7 * 6
divisao = 32/4
potencia = 7**2

print ("soma", soma)
print("multiplicacao", multiplicacao)
print("divisao", divisao)
print("potencia", potencia)